service: serverless-test
app: testapp1
org: cybercat

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  environment:
    DYNAMODB_TABLE: serverless-test
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Scan
        - dynamodb:UpdateItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:*:*:table/${self:provider.environment.DYNAMODB_TABLE}"

resources:
  Resources:
    songsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: songName
            AttributeType: S
        KeySchema:
          - AttributeName: songName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-finch

custom:
  client:
    bucketName: sahan-serverless-test009
    distributionFolder: frontend
    errorDocument: index.html
